x64\Release\WordDistance casa casa >Sortida.txt
x64\Release\WordDistance casa cassa >Sortida.txt
x64\Release\WordDistance casa caa >>Sortida.txt
x64\Release\WordDistance casa caxa >>Sortida.txt
x64\Release\WordDistance casa caas >>Sortida.txt
x64\Release\WordDistance 123 321 >>Sortida.txt
x64\Release\WordDistance 1234 4321 >>Sortida.txt
x64\Release\WordDistance palindromo planirdmoo >>Sortida.txt
x64\Release\WordDistance coche cotche >>Sortida.txt
x64\Release\WordDistance calimocho clmch >>Sortida.txt
