x64\Debug\WordDistance casa casa >Sortida.txt
x64\Debug\WordDistance casa cassa >Sortida.txt
x64\Debug\WordDistance casa caa >>Sortida.txt
x64\Debug\WordDistance casa caxa >>Sortida.txt
x64\Debug\WordDistance casa caas >>Sortida.txt
x64\Debug\WordDistance 123 321 >>Sortida.txt
x64\Debug\WordDistance 1234 4321 >>Sortida.txt
x64\Debug\WordDistance palindromo planirdmoo >>Sortida.txt
x64\Debug\WordDistance coche cotche >>Sortida.txt
x64\Debug\WordDistance calimocho clmch >>Sortida.txt
